name: Apple M1 Full Benchmark
on: [push]
jobs:
  bench-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Compila TITAN Full
      run: make
    - name: Esegui Benchmark
      run: ./titan_m1_bench
