name: Apple M1 Benchmark
on: [push]
jobs:
  bench-macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Compila su M1
      run: |
        chmod +x build_m1.sh
        ./build_m1.sh
    - name: Esegui Benchmark
      run: ./titan_arm_bench_m1
